#!/bin/bash

# Bu skript 'hello' adlı faylın icazələrini dəyişdirir.
# Sahibə və qrup sahibinə icra icazəsi, digərlərinə isə oxuma icazəsi verir.
chmod ug+x,o+r hello
#!/bin/bash
chmod ug+x,o+r hello
